config/routes.rb
Rails.application.routes.draw do
  get 'actors/index'

  get 'actress/index' => "actress#index"
  get 'actress/chichi' => "actress#chichi"
  post 'actress/create' => 'actress#create'

  get 'users/index' => "users#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/actress.rb
class Actress < ActiveRecord::Base


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ActiveRecord::Base

end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  def index
  end
end

app/controllers/actress_controller.rb
class ActressController < ApplicationController
  def index
    @actress = Actress.new
    @actresses = Actress.all
  end

  def create
    @actress = Actress.new(actress_params)
    @actress.save
    redirect_to actress_index_path
  end

  def chichi
    @students = ["有村","喜久山","藤田"]
  end

  private
  def actress_params
    params.require(:actress).permit(:name, :age)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UserController < ApplicationController
  def user

  end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/actors/index.html.erb
<h1>Actors#index</h1>
<p>Find me in app/views/actors/index.html.erb</p>

app/views/actress/chichi.html.erb
<h1>乳</h1>
<% @students.each do |student| %>
  <%= student %>
<% end %>

app/views/actress/index.html.erb
<h1>MM号　ライフセーバー</h1>
<img src="/_5812d23841f51　ライフセーバー.jpeg">

<%= form_for @actress, url: actress_create_path do |f| %>
  <%= f.text_field :name %>
  <%= f.number_field :age %>
  <%= f.submit %>
<% end %>

<% @actresses.each do |actress| %>
  <%= actress.name %><br>
  <%= actress.age %><br><br>
<% end %>

app/views/home/index.html.erb
<h1>MM号　ライフセーバー</h1>
<img src="/_5812d23841f51　ライフセーバー.jpeg">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TweetApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>